#!/bin/bash

# Check if the number of parameters is correct
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi


# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i '~/.ssh/school' /path/to/ssh/some_page.html ubuntu 342224-web-01@10.251.02

# Check the exit status of the scp command
if [ "$?" -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
