#!/usr/bin/env bash
# configure an Nginx server to listen on port 80

# create a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory
ln -sf /etc/ngnx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process to
kill "$(pgrep 'nginx' | head -1)"
