#!/bin/env bash

sudo vi /etc/ufw/sysctl.conf
net/ipv4/ip_forward=1

sudo sysctl -p
sudo ufw allow 8080/tcp
sudo ufw status

#we will have a Forwarding rule
sudo vi /etc/ufw/before.rules

*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT

# disable ufw and enable it again for changes to take place
sudo ufw Disable
sudo ufw Enable

sudo ufw status
