#!/usr/sbin/env bash
# ~/.ssh/config

Host your_server_hostname_or_ip
  IdentityFile ~/.ssh/school
  PasswordAuthentication no

# Use the ssh command with single-character flags
ssh -i ~/.ssh/school ubuntu@10.251.0.23

